### ISSUE TITLE
This package seems to break when running React v17

### ISSUE THREAD

**Issue by matis-dk** [JaniAnttonen/react-select-native#14]
I'm getting the following error when using this package v.1.0.0 with React v17.
https://reactjs.org/warnings/invalid-hook-call-warning.html

It seems to be related to a "Duplicate React" import issue. According to the documentation, you have to make sure that React is getting specified as a peer dependency, and not as a dependency.

Codesandbox playground:
https://codesandbox.io/s/react-select-native-e9n3n?file=/src/App.js

**Comment by JaniAnttonen** [comment]
Hello, thanks for your input! Published a new version, `2.0.0`, which should work with React 17. Closing this if that's true :)

**Comment by matis-dk** [comment]
Excellent, works perfectly!
